// ── 유튜브 채널 별칭(보정) 테이블 ──────────────────────────────────────
// 유튜브 검색/음역(dashboard.js의 _transliterateByLanguagePolicy)만으로는
// 못 찾는 채널이 있다 — 실제 채널명과 발음이 닮지 않은, 팬덤 내에서만
// 통용되는 애칭인 경우다(예: "hebi."를 한국 팬은 "헤비", 일본 팬은
// "ヘビ"로 부름). 이 테이블이 그런 애칭을 실제 채널명으로 보정해
// 검색어에 함께 실어 보낸다.
//
// content_scripts 목록에서 dashboard.js보다 먼저 로드되어
// window.CHEESE_EYES_YOUTUBE_ALIASES에 (별칭 → 실제 채널명) Map을
// 채운다. dashboard.js의 PlatformAdapters.youtube._buildKeywordMatchTerms가
// 이 Map을 조회한다.
//
// 추가 방법: ENTRIES에 { name: '실제 채널명', aliases: [...] } 추가.
// name은 검색 API에 보낼 정확한 채널명 표기(대소문자/문장부호 포함
// 원문 그대로), aliases는 사람들이 검색창에 실제로 입력할 법한
// 애칭/음역/오기 표기들.
//
// 한국 버튜버는 대개 SOOP/치지직에서 라이브하고 유튜브엔 편집 영상만
// 올린다. 이 테이블은 유튜브 라이브 검색 보정용이므로, 유튜브 동시송출이
// 실제 확인된 경우에만 등록한다(예: hebi.) — 등록 전 반드시 확인할 것.
//
// 현재 648명(버튜버 503 + 휴먼 스트리머 145, 목표 1000명 중 진행 중).
// 버튜버 503명(500명 목표分 완료, 1~5차)은 호로라이브 전 브랜치 +
// 니지산지 JP/EN/ID/KR + VSPO!(JP+EN) + 774 inc. + Phase Connect +
// Re:AcT(JP+KR+Gaming) + .LIVE+VPI Cafe + StelLive + Nyantasia! + SCARZ
// + Million Production + MythosHQ + V&U + Varium + Dynasty V +
// MOE!Live + Vkano 현역 + 유튜브 라이브 확인된 한국 버튜버 1명. 소속
// 자체가 유튜브 라이브 중심인 곳은 개인별 동시송출 확인 없이 등록.
// 근거:
//   - 1차분: 나무위키
//   - 2~3차분(니지산지 JP/EN/ID): 니지산지 위키(nijisanji.miraheze.org,
//     2025-06-28 revision)의 졸업/은퇴(R)·휴업(H) 표기로 현역만 필터링
//   - 3차분(VSPO!): virtualyoutuber.fandom.com/wiki/VSPO! — 중국 지사는
//     2025-10-15 해체(MUGEN LIVE로 이적)되어 제외, 휴업(H)도 제외
//   - 4~5차분(774 inc./Phase Connect/Re:AcT/.LIVE/StelLive/Nyantasia!/
//     SCARZ/Million Production/MythosHQ/V&U/Varium/Dynasty V/
//     MOE!Live/Vkano/니지산지 KR): virtualyoutuber.fandom.com 각
//     에이전시 문서 — 탈퇴(F)·은퇴(R)·휴업(H) 제외. 니지산지 KR은
//     StelLive 사례(국적과 무관하게 일본식 예명·로마자 채널명)를 따라
//     로마자로 등록 — Min Suha처럼 실채널명이 한글(민수하)인 경우가
//     있을 수 있어 오탐 시 교정 필요
// 보류: VShojo — 다수가 트위치 중심(Ironmouse, Vei 등)이라 개인별
// 유튜브 라이브 확인 전까지 보류.
// 다음 목표: 500 → 1000명, 후반 500명은 해외 휴먼 유튜버 스트리머로 채울 예정.
(function () {
  const ENTRIES = [
    // 유튜브 라이브 진행이 확인된 한국 버튜버.
    { name: 'hebi.', aliases: ['헤비', 'ヘビ'] },

    // ── Hololive JP ──────────────────────────────────────────────────
    { name: 'Tokino Sora', aliases: ['토키노 소라'] },
    { name: 'Roboco', aliases: ['로보코'] },
    { name: 'Sakura Miko', aliases: ['사쿠라 미코'] },
    { name: 'Hoshimachi Suisei', aliases: ['호시마치 스이세이'] },
    { name: 'Aki Rosenthal', aliases: ['아키 로젠탈'] },
    { name: 'Akai Haato', aliases: ['아카이 하아토'] },
    { name: 'Shirakami Fubuki', aliases: ['시라카미 후부키'] },
    { name: 'Natsuiro Matsuri', aliases: ['나츠이로 마츠리'] },
    { name: 'Nakiri Ayame', aliases: ['나키리 아야메'] },
    { name: 'Yuzuki Choco', aliases: ['유즈키 초코'] },
    { name: 'Oozora Subaru', aliases: ['오오조라 스바루'] },
    { name: 'Minato Aqua', aliases: ['미나토 아쿠아'] },
    { name: 'Murasaki Shion', aliases: ['무라사키 시온'] },
    { name: 'Ookami Mio', aliases: ['오오카미 미오'] },
    { name: 'Nekomata Okayu', aliases: ['네코마타 오카유'] },
    { name: 'Inugami Korone', aliases: ['이누가미 코로네'] },
    { name: 'Usada Pekora', aliases: ['우사다 페코라'] },
    { name: 'Shiranui Flare', aliases: ['시라누이 후레아'] },
    { name: 'Shirogane Noel', aliases: ['시로가네 노엘'] },
    { name: 'Houshou Marine', aliases: ['호쇼 마린'] },
    { name: 'Tsunomaki Watame', aliases: ['츠노마키 와타메'] },
    { name: 'Tokoyami Towa', aliases: ['토코야미 토와'] },
    { name: 'Himemori Luna', aliases: ['히메모리 루나'] },
    { name: 'Yukihana Lamy', aliases: ['유키하나 라미'] },
    { name: 'Momosuzu Nene', aliases: ['모모스즈 네네'] },
    { name: 'Shishiro Botan', aliases: ['시시로 보탄'] },
    { name: 'Omaru Polka', aliases: ['오마루 폴카'] },
    { name: 'La+ Darknesss', aliases: ['라플라스 다크니스', 'Laplus Darknesss'] },
    { name: 'Takane Lui', aliases: ['타카네 루이'] },
    { name: 'Hakui Koyori', aliases: ['하쿠이 코요리'] },
    { name: 'Kazama Iroha', aliases: ['카자마 이로하'] },

    // ── Hololive Indonesia ───────────────────────────────────────────
    { name: 'Ayunda Risu', aliases: ['아윤다 리스'] },
    { name: 'Moona Hoshinova', aliases: ['무나 호시노바'] },
    { name: 'Airani Iofifteen', aliases: ['아이라니 이오피프틴'] },
    { name: 'Kureiji Ollie', aliases: ['쿠레이지 올리'] },
    { name: 'Anya Melfissa', aliases: ['아냐 멜핏사'] },
    { name: 'Pavolia Reine', aliases: ['파볼리아 레이네'] },
    { name: 'Vestia Zeta', aliases: ['베스티아 제타'] },
    { name: 'Kaela Kovalskia', aliases: ['카엘라 코발스키아'] },
    { name: 'Kobo Kanaeru', aliases: ['코보 카나에루'] },

    // ── Hololive English ─────────────────────────────────────────────
    { name: 'Mori Calliope', aliases: ['모리 칼리오페'] },
    { name: 'Takanashi Kiara', aliases: ['타카나시 키아라'] },
    { name: "Ninomae Ina'nis", aliases: ['니노마에 이나니스'] },
    { name: 'IRyS', aliases: ['아이리스'] },
    { name: 'Ouro Kronii', aliases: ['오로 크로니'] },
    { name: 'Hakos Baelz', aliases: ['하코스 벨즈'] },
    { name: 'Shiori Novella', aliases: ['시오리 노벨라'] },
    { name: 'Koseki Bijou', aliases: ['코세키 비쥬'] },
    { name: 'Nerissa Ravencroft', aliases: ['네리사 레이븐크로프트'] },
    { name: 'Fuwawa Abyssgard', aliases: ['후와와 어비스가드'] },
    { name: 'Mococo Abyssgard', aliases: ['모코코 어비스가드'] },
    { name: 'Elizabeth Rose Bloodflame', aliases: ['엘리자베스 로즈 블러드플레임'] },
    { name: 'Gigi Murin', aliases: ['지지 무린'] },
    { name: 'Cecilia Immergreen', aliases: ['세실리아 이머그린'] },
    { name: 'Raora Panthera', aliases: ['라오라 판테라'] },

    // ── Hololive DEV_IS ──────────────────────────────────────────────
    { name: 'Otonose Kanade', aliases: ['오토노세 카나데'] },
    { name: 'Ichijou Ririka', aliases: ['이치조 리리카'] },
    { name: 'Juufuutei Raden', aliases: ['주우후테이 라덴'] },
    { name: 'Todoroki Hajime', aliases: ['토도로키 하지메'] },
    { name: 'Isaki Riona', aliases: ['이사키 리오나'] },
    { name: 'Koganei Niko', aliases: ['코가네이 니코'] },
    { name: 'Mizumiya Su', aliases: ['미즈미야 스우'] },
    { name: 'Rindo Chihaya', aliases: ['린도 치하야'] },
    { name: 'Kikirara Vivi', aliases: ['키키라라 비비'] },

    // ── HOLOSTARS JP ─────────────────────────────────────────────────
    { name: 'Kanade Izuru', aliases: ['카나데 이즈루'] },
    { name: 'Astel Leda', aliases: ['아스텔 레다'] },
    { name: 'Yukoku Roberu', aliases: ['유코쿠 로베루'] },
    { name: 'Aragami Oga', aliases: ['아라가미 오가'] },
    { name: 'Yatogami Fuma', aliases: ['야토가미 후마'] },
    { name: 'Utsugi Uyu', aliases: ['우츠기 우유'] },

    // ── HOLOSTARS English ────────────────────────────────────────────
    { name: 'Regis Altare', aliases: ['리지스 알테어'] },
    { name: 'Axel Syrios', aliases: ['악셀 시리오스'] },
    { name: 'Gavis Bettel', aliases: ['가비스 베텔'] },
    { name: 'Machina X Flayon', aliases: ['마키나 X 플레온'] },
    { name: 'Banzoin Hakka', aliases: ['반조인 핫카'] },
    { name: 'Josuiji Shinri', aliases: ['조스이지 신리'] },
    { name: 'Jurard T Rexford', aliases: ['쥐라르드 T 렉스포드'] },
    { name: 'Goldbullet', aliases: ['골드불릿'] },
    { name: 'Octavio', aliases: ['옥타비오'] },
    { name: 'Crimson Ruze', aliases: ['크림즌 루즈'] },

    // ── Hololive Announcer(holoAN) ───────────────────────────────────
    { name: 'Izuki Michiru', aliases: ['이즈키 미치루'] },
    { name: 'Hanazono Sayaka', aliases: ['하나조노 사야카'] },
    { name: 'Kazeshiro Yuki', aliases: ['카제시로 유키'] },

    // ── Nijisanji JP (메인 브랜치, 1기 ~ VOLTACTION) ───────────────────
    { name: 'Tsukino Mito', aliases: ['츠키노 미토'] },
    { name: 'Shibuya Hajime', aliases: ['시부야 하지메'] },
    { name: 'Higuchi Kaede', aliases: ['히구치 카에데'] },
    { name: 'Shizuka Rin', aliases: ['시즈카 린'] },
    { name: 'Moira', aliases: ['모이라'] },
    { name: 'Elu', aliases: ['엘루'] },
    { name: 'Ienaga Mugi', aliases: ['이에나가 무기'] },
    { name: 'Mononobe Alice', aliases: ['모노노베 아리스'] },
    { name: 'Kenmochi Toya', aliases: ['켄모치 토야'] },
    { name: 'Morinaka Kazaki', aliases: ['모리나카 카자키'] },
    { name: 'Fushimi Gaku', aliases: ['후시미 가쿠'] },
    { name: 'Gilzaren III', aliases: ['길자렌 3세'] },
    { name: 'Fumino Tamaki', aliases: ['후미노 타마키'] },
    { name: 'Ushimi Ichigo', aliases: ['우시미 이치고'] },
    { name: 'Yuuhi Riri', aliases: ['유우히 리리'] },
    { name: 'Kanae', aliases: ['카나에'] },
    { name: 'Akabane Youko', aliases: ['아카바네 요우코'] },
    { name: 'Sasaki Saku', aliases: ['사사키 사쿠'] },
    { name: 'Honma Himawari', aliases: ['혼마 히마와리'] },
    { name: 'Makaino Ririmu', aliases: ['마카이노 리림'] },
    { name: 'Kuzuha', aliases: ['쿠즈하'] },
    { name: 'Shiina Yuika', aliases: ['시이나 유이카'] },
    { name: 'Dola', aliases: ['돌라'] },
    { name: 'Hanabatake Chaika', aliases: ['하나바타케 차이카'] },
    { name: 'Ryushen', aliases: ['류센'] },
    { name: 'Sister Claire', aliases: ['시스터 클레어'] },
    { name: 'Suzuki Masaru', aliases: ['스즈키 마사루'] },
    { name: 'Todoroki Kyoko', aliases: ['토도로키 쿄코'] },
    { name: 'Uzuki Kou', aliases: ['우즈키 코우'] },
    { name: 'Yashiro Kizuku', aliases: ['야시로 키즈쿠'] },
    { name: 'Harusaki Air', aliases: ['하루사키 에아'] },
    { name: 'Kanda Shoichi', aliases: ['칸다 쇼이치'] },
    { name: 'Amemori Sayo', aliases: ['아메모리 사요'] },
    { name: 'Takamiya Rion', aliases: ['타카미야 리온'] },
    { name: 'Asuka Hina', aliases: ['아스카 히나'] },
    { name: 'Maimoto Keisuke', aliases: ['마이모토 케이스케'] },
    { name: 'Debidebi Debiru', aliases: ['데비데비 데비루'] },
    { name: 'Rindou Mikoto', aliases: ['린도우 미코토'] },
    { name: 'Joe Rikiichi', aliases: ['죠 리키이치'] },
    { name: 'Machita Chima', aliases: ['마치타 치마'] },
    { name: 'Sakura Ritsuki', aliases: ['사쿠라 리츠키'] },
    { name: 'Belmond Banderas', aliases: ['벨몬드 반데라스'] },
    { name: 'Yaguruma Rine', aliases: ['야구루마 리네'] },
    { name: 'Yumeoi Kakeru', aliases: ['유메오이 카케루'] },
    { name: 'Kuroi Shiba', aliases: ['쿠로이 시바'] },
    { name: 'Onomachi Haruka', aliases: ['오노마치 하루카'] },
    { name: 'Inui Toko', aliases: ['이누이 토코'] },
    { name: 'Ange Katrina', aliases: ['안쥬 카트리나'] },
    { name: 'Lize Helesta', aliases: ['리제 헤레스타'] },
    { name: 'Saegusa Akina', aliases: ['사에구사 아키나'] },
    { name: 'Aizono Manami', aliases: ['아이조노 마나미'] },
    { name: 'Yukishiro Mahiro', aliases: ['유키시로 마히로'] },
    { name: 'Ex Albio', aliases: ['엑스 알비오'] },
    { name: 'Levi Elipha', aliases: ['레비 엘리파'] },
    { name: 'Hayama Marin', aliases: ['하야마 마린'] },
    { name: 'Nui Sociere', aliases: ['누이 소시에르'] },
    { name: 'Hakase Fuyuki', aliases: ['하카세 후유키'] },
    { name: 'Yorumi Rena', aliases: ['요루미 레나'] },
    { name: 'Kagami Hayato', aliases: ['카가미 하야토'] },
    { name: 'Ars Almal', aliases: ['아르스 아르말'] },
    { name: 'Amamiya Kokoro', aliases: ['아마미야 코코로'] },
    { name: 'Eli Conifer', aliases: ['엘리 코니퍼'] },
    { name: 'Ratna Petit', aliases: ['라트나 프티'] },
    { name: 'Sukoya Kana', aliases: ['스코야 카나'] },
    { name: 'Hayase Sou', aliases: ['하야세 소우'] },
    { name: 'Shellin Burgundy', aliases: ['셸린 버건디'] },
    { name: 'Fumi', aliases: ['후미'] },
    { name: 'Yamagami Karuta', aliases: ['야마가미 카루타'] },
    { name: 'Hoshikawa Sara', aliases: ['호시카와 사라'] },
    { name: 'Emma★August', aliases: ['엠마 오거스트'] },
    { name: 'Luis Cammy', aliases: ['루이스 캐미'] },
    { name: 'Matsukai Mao', aliases: ['마츠카이 마오'] },
    { name: 'Gwelu Os Gar', aliases: ['그웰루 오스 가르'] },
    { name: 'Shirayuki Tomoe', aliases: ['시라유키 토모에'] },
    { name: 'Fuwa Minato', aliases: ['후와 미나토'] },
    { name: 'Kurusu Natsume', aliases: ['쿠루스 나츠메'] },
    { name: 'Naraka', aliases: ['나라카'] },
    { name: 'Mashiro Meme', aliases: ['마시로 메메'] },
    { name: 'Furen E Lustario', aliases: ['후렌 E 루스타리오'] },
    { name: 'Ibrahim', aliases: ['이브라힘'] },
    { name: 'Genzuki Tojiro', aliases: ['겐즈키 토지로'] },
    { name: 'Nagao Kei', aliases: ['나가오 케이'] },
    { name: 'Kaida Haru', aliases: ['카이다 하루'] },
    { name: 'Sorahoshi Kirame', aliases: ['소라호시 키라메'] },
    { name: 'Suo Sango', aliases: ['스오 산고'] },
    { name: 'Kitakoji Hisui', aliases: ['키타코지 히스이'] },
    { name: 'Todo Kohaku', aliases: ['토도 코하쿠'] },
    { name: 'Nishizono Chigusa', aliases: ['니시조노 치구사'] },
    { name: 'Lauren Iroas', aliases: ['로렌 이로아스'] },
    { name: 'Leos Vincent', aliases: ['레오스 빈센트'] },
    { name: 'Oliver Evans', aliases: ['올리버 에반스'] },
    { name: 'Lain Paterson', aliases: ['레인 패터슨'] },
    { name: 'Umise Yotsuha', aliases: ['우미세 요츠하'] },
    { name: 'Amagase Muyu', aliases: ['아마가세 무유'] },
    { name: 'Ponto Nei', aliases: ['폰토 네이'] },
    { name: 'Hyakumantenbara Salome', aliases: ['햐쿠만텐바라 사로메'] },
    { name: 'Fura Kanato', aliases: ['후라 카나토'] },
    { name: 'Watarai Hibari', aliases: ['와타라이 히바리'] },
    { name: 'Shikinagi Akira', aliases: ['시키나기 아키라'] },
    { name: 'Seraph Dazzlegarden', aliases: ['세라프 대즐가든'] },

    // ── Nijisanji JP (메인 브랜치, Idios ~ Super Elite) ─────────────────
    { name: 'Igarashi Rika', aliases: ['이가라시 리카'] },
    { name: 'Koshimizu Toru', aliases: ['코시미즈 토루'] },
    { name: 'Ishigami Nozomi', aliases: ['이시가미 노조미'] },
    { name: 'Sophia Valentine', aliases: ['소피아 발렌타인'] },
    { name: 'Kuramochi Meruto', aliases: ['쿠라모치 메루토'] },
    { name: 'Kaburaki Roco', aliases: ['카부라키 로코'] },
    { name: 'Shishido Akari', aliases: ['시시도 아카리'] },
    { name: 'Akagi Wen', aliases: ['아카기 웬'] },
    { name: 'Usami Rito', aliases: ['우사미 리토'] },
    { name: 'Hibachi Mana', aliases: ['히바치 마나'] },
    { name: 'Saiki Ittetsu', aliases: ['사이키 잇테츠'] },
    { name: 'Murakumo Kagetsu', aliases: ['무라쿠모 카게츠'] },
    { name: 'Hoshirube Sho', aliases: ['호시루베 쇼'] },
    { name: 'Koyanagi Rou', aliases: ['코야나기 로우'] },
    { name: 'Inami Rai', aliases: ['이나미 라이'] },
    { name: 'Tachitsute Toto', aliases: ['타치츠테 토토'] },
    { name: 'Shioriha Ruri', aliases: ['시오리하 루리'] },
    { name: 'Milan Kestrel', aliases: ['밀란 케스트럴'] },
    { name: 'Kitami Yusei', aliases: ['키타미 유세이'] },
    { name: 'Kaisei', aliases: ['카이세이'] },
    { name: 'Sakaki Ness', aliases: ['사카키 네스'] },
    { name: 'Shiga Riko', aliases: ['시가 리코'] },
    { name: 'Tamanoi Nana', aliases: ['타마노이 나나'] },
    { name: 'Kisara', aliases: ['키사라'] },
    { name: 'Kozue Mone', aliases: ['코즈에 모네'] },
    { name: 'Lunlun', aliases: ['룬룬'] },
    { name: 'Nanase Suzuna', aliases: ['나나세 스즈나'] },
    { name: 'Saotome Berry', aliases: ['사오토메 베리'] },
    { name: 'Kirara Tamako', aliases: ['키라라 타마코'] },
    { name: 'Sakayori Soma', aliases: ['사카요리 소마'] },
    { name: 'Nagisa Trout', aliases: ['나기사 트라우트'] },
    { name: 'Hitotsubashi Ayato', aliases: ['히토츠바시 아야토'] },
    { name: 'Itsuki Sakyo', aliases: ['이츠키 사쿄'] },

    // ── Nijisanji EN ──────────────────────────────────────────────────
    { name: 'Elira Pendora', aliases: ['엘리라 펜도라'] },
    { name: 'Finana Ryugu', aliases: ['피나나 류구'] },
    { name: 'Rosemi Lovelock', aliases: ['로제미 러브록'] },
    { name: 'Petra Gurin', aliases: ['페트라 구린'] },
    { name: 'Millie Parfait', aliases: ['밀리 파르페'] },
    { name: 'Enna Alouette', aliases: ['엔나 알루엣'] },
    { name: 'Reimu Endou', aliases: ['레이무 엔도우'] },
    { name: 'Luca Kaneshiro', aliases: ['루카 카네시로'] },
    { name: 'Shu Yamino', aliases: ['슈 야미노'] },
    { name: 'Vox Akuma', aliases: ['복스 아쿠마'] },
    { name: 'Sonny Brisko', aliases: ['서니 브리스코'] },
    { name: 'Uki Violeta', aliases: ['우키 비올레타'] },
    { name: 'Alban Knox', aliases: ['알반 녹스'] },
    { name: 'Maria Marionette', aliases: ['마리아 마리오네트'] },
    { name: 'Aia Amare', aliases: ['아이아 아마레'] },
    { name: 'Aster Arcadia', aliases: ['아스터 아르카디아'] },
    { name: 'Scarle Yonaguni', aliases: ['스칼레 요나구니'] },
    { name: 'Ren Zotto', aliases: ['렌 조토'] },
    { name: 'Doppio Dropscythe', aliases: ['도피오 드롭사이스'] },
    { name: 'Meloco Kyoran', aliases: ['멜로코 쿄란'] },
    { name: 'Ver Vermillion', aliases: ['베르 버밀리언'] },
    { name: 'Vezalius Bandage', aliases: ['베잘리우스 반데이지'] },
    { name: 'Vantacrow Bringer', aliases: ['반타크로우 브링어'] },
    { name: 'Yu Q. Wilson', aliases: ['유 Q. 윌슨'] },
    { name: 'Claude Clawmark', aliases: ['클로드 클로마크'] },
    { name: 'Ryoma Barrenwort', aliases: ['료마 배런워트'] },
    { name: 'Klara Charmwood', aliases: ['클라라 참우드'] },
    { name: 'Zeal Ginjoka', aliases: ['질 긴조카'] },
    { name: 'Freodore', aliases: ['프레오도어'] },
    { name: 'Seible', aliases: ['세이블'] },
    { name: 'Kaelix Debonair', aliases: ['케일릭스 데보네어'] },

    // ── Nijisanji ID ──────────────────────────────────────────────────
    { name: 'Hana Macchia', aliases: ['하나 마키아'] },
    { name: 'Rai Galilei', aliases: ['라이 갈릴레이'] },
    { name: 'Layla Alstroemeria', aliases: ['레일라 알스트로메리아'] },
    { name: 'Etna Crimson', aliases: ['에트나 크림슨'] },
    { name: 'Nagisa Arcinia', aliases: ['나기사 아르시니아'] },
    { name: 'Derem Kado', aliases: ['데렘 카도'] },

    // ── VSPO! (JP + English) ─────────────────────────────────────────
    { name: 'Kaga Sumire', aliases: ['카가 스미레'] },
    { name: 'Kaga Nazuna', aliases: ['카가 나즈나'] },
    { name: 'Kogara Toto', aliases: ['코가라 토토'] },
    { name: 'Ichinose Uruha', aliases: ['이치노세 우루하'] },
    { name: 'Kurumi Noah', aliases: ['쿠루미 노아'] },
    { name: 'Tachibana Hinano', aliases: ['타치바나 히나노'] },
    { name: 'Kisaragi Ren', aliases: ['키사라기 렌'] },
    { name: 'Tosaki Mimi', aliases: ['토사키 미미'] },
    { name: 'Asumi Sena', aliases: ['아스미 세나'] },
    { name: 'Hanabusa Lisa', aliases: ['하나부사 리사'] },
    { name: 'Kaminari Qpi', aliases: ['카미나리 큐피'] },
    { name: 'Yakumo Beni', aliases: ['야쿠모 베니'] },
    { name: 'Aizawa Ema', aliases: ['아이자와 에마'] },
    { name: 'Shinomiya Runa', aliases: ['시노미야 루나'] },
    { name: 'Nekota Tsuna', aliases: ['네코타 츠나'] },
    { name: 'Shiranami Ramune', aliases: ['시라나미 라무네'] },
    { name: 'Komori Met', aliases: ['코모리 메토'] },
    { name: 'Yumeno Akari', aliases: ['유메노 아카리'] },
    { name: 'Yano Kuromu', aliases: ['야노 쿠로무'] },
    { name: 'Tsumugi Kokage', aliases: ['츠무기 코카게'] },
    { name: 'Sendo Yuuhi', aliases: ['센도 유우히'] },
    { name: 'Choya Hanabi', aliases: ['초야 하나비'] },
    { name: 'Amayui Moka', aliases: ['아마유이 모카'] },
    { name: 'Ginjo Saine', aliases: ['긴죠 사이네'] },
    { name: 'Tatsumaki Chise', aliases: ['타츠마키 치세'] },
    { name: 'Remia Aotsuki', aliases: ['레미아 아오츠키'] },
    { name: 'Arya Kuroha', aliases: ['아리아 쿠로하'] },
    { name: 'Jira Jisaki', aliases: ['지라 지사키'] },
    { name: 'Narin Mikure', aliases: ['나린 미쿠레'] },
    { name: 'Riko Solari', aliases: ['리코 솔라리'] },
    { name: 'Juno Umezono', aliases: ['주노 우메조노'] },

    // ── 774 inc. (Nanashiinku) ────────────────────────────────────────
    { name: 'Inaba Haneru', aliases: ['이나바 하네루'] },
    { name: 'Souya Ichika', aliases: ['소우야 이치카'] },
    { name: 'Kazami Kuku', aliases: ['카자미 쿠쿠'] },
    { name: 'Yunohara Izumi', aliases: ['유노하라 이즈미'] },
    { name: 'Seshima Rui', aliases: ['세시마 루이'] },
    { name: 'Hira Hikari', aliases: ['히라 히카리'] },
    { name: 'Konan Mia', aliases: ['코난 미아'] },
    { name: 'Tsukinoki Tirol', aliases: ['츠키노키 티롤'] },
    { name: 'Shimamura Charlotte', aliases: ['시마무라 샬롯'] },
    { name: 'Saionji Mary', aliases: ['사이온지 마리'] },
    { name: 'Sekishiro Mico', aliases: ['세키시로 미코'] },
    { name: 'And Uge', aliases: ['안도 우게'] },
    { name: 'Kanade Kanon', aliases: ['카나데 카논'] },
    { name: 'Kisaki Anko', aliases: ['키사키 안코'] },
    { name: 'Ryugasaki Rene', aliases: ['류가사키 레네'] },
    { name: 'Hebiyoi Tier', aliases: ['헤비요이 티어'] },
    { name: 'Akane Canna', aliases: ['아카네 칸나'] },
    { name: 'Ieiri Popo', aliases: ['이에이리 포포'] },
    { name: 'Kohaku Yuri', aliases: ['코하쿠 유리'] },
    { name: 'Amaui', aliases: ['아마우이'] },
    { name: 'Hinata Mashu', aliases: ['히나타 마슈'] },
    { name: 'Amatsuna Sasaha', aliases: ['아마츠나 사사하'] },
    { name: 'Kasukane Shino', aliases: ['카스카네 시노'] },
    { name: 'Uruwashi Ririri', aliases: ['우루와시 리리리'] },
    { name: 'Azri', aliases: ['아즈리'] },
    { name: 'Rokusho Kureha', aliases: ['로쿠쇼 쿠레하'] },
    { name: 'Coco Jester', aliases: ['코코 제스터'] },
    { name: 'Shionari Mirine', aliases: ['시오나리 미리네'] },
    { name: 'Nanase Ray', aliases: ['나나세 레이'] },
    { name: 'Pikamaru NS-PT01', aliases: ['피카마루 NS-PT01'] },

    // ── Phase Connect ─────────────────────────────────────────────────
    { name: 'Rinkou Ashelia', aliases: ['린코우 아셀리아'] },
    { name: 'Pipkin Pippa', aliases: ['핍킨 피파'] },
    { name: 'Tenma Maemi', aliases: ['텐마 마에미'] },
    { name: 'Fujikura Uruka', aliases: ['후지쿠라 우루카'] },
    { name: 'Utatane Nasa', aliases: ['우타타네 나사'] },
    { name: 'Hakushika Iori', aliases: ['하쿠시카 이오리'] },
    { name: 'Shisui Michiru', aliases: ['시스이 미치루'] },
    { name: 'Kaneko Lumi', aliases: ['카네코 루미'] },
    { name: 'Dizzy Dokuro', aliases: ['디지 도쿠로'] },
    { name: 'Jelly Hoshiumi', aliases: ['젤리 호시우미'] },
    { name: 'Ember Amane', aliases: ['엠버 아마네'] },
    { name: 'Clio Aite', aliases: ['클리오 아이테'] },
    { name: 'Mari Mari', aliases: ['마리 마리'] },
    { name: 'Eepy Sleepy', aliases: ['이피 슬리피'] },
    { name: 'Remilia Nephys', aliases: ['레밀리아 네피스'] },
    { name: 'Chisaka Airi', aliases: ['치사카 아이리'] },
    { name: 'Amanogawa Shiina', aliases: ['아마노가와 시이나'] },
    { name: 'Himemiya Rie', aliases: ['히메미야 리에'] },
    { name: 'Makina Erina', aliases: ['마키나 에리나'] },
    { name: 'Komachi Panko', aliases: ['코마치 판코'] },
    { name: 'Runie Ruse', aliases: ['루니 루즈'] },
    { name: 'Muu Muyu', aliases: ['무우 무유'] },
    { name: 'Eimi Isami', aliases: ['에이미 이사미'] },
    { name: 'Saya Sairroxs', aliases: ['사야 사이록스'] },
    { name: 'Nitya Nil', aliases: ['니티아 닐'] },
    { name: 'Wilhelmina Frost', aliases: ['윌헬미나 프로스트'] },
    { name: 'Sinon Sinfonia', aliases: ['시논 신포니아'] },
    { name: 'Malice Evermore', aliases: ['말리스 에버모어'] },
    { name: 'Bibi Biscuit', aliases: ['비비 비스킷'] },
    { name: 'Kannagi Loki', aliases: ['칸나기 로키'] },
    { name: 'Ayase Yuu', aliases: ['아야세 유우'] },
    { name: 'Gram Pico', aliases: ['그램 피코'] },
    { name: 'Kokoromo Memory', aliases: ['코코로모 메모리'] },

    // ── Re:AcT (JP 메인) ──────────────────────────────────────────────
    { name: 'Shishigami Leona', aliases: ['시시가미 레오나'] },
    { name: 'Mizugame Mia', aliases: ['미즈가메 미아'] },
    { name: 'Yumekawa Kanau', aliases: ['유메카와 카나우'] },
    { name: 'Marumochi Tsukimi', aliases: ['마루모치 츠키미'] },
    { name: 'Tsukushi Aria', aliases: ['츠쿠시 아리아'] },
    { name: 'Nekono Yukino', aliases: ['네코노 유키노'] },
    { name: 'Sumeragi Rose', aliases: ['스메라기 로즈'] },
    { name: 'Usuwa Suu', aliases: ['우스와 스우'] },
    { name: 'Makoh Lisa', aliases: ['마코 리사'] },
    { name: 'Otogi Nemu', aliases: ['오토기 네무'] },
    { name: 'Shirane Yuki', aliases: ['시라네 유키'] },
    { name: 'Anya Kumori', aliases: ['안야 쿠모리'] },
    { name: 'Layla Sama', aliases: ['레일라 사마'] },
    { name: 'Suzuhana Inori', aliases: ['스즈하나 이노리'] },
    { name: 'Otoha Sora', aliases: ['오토하 소라'] },
    { name: 'Kannagi Anna', aliases: ['칸나기 안나'] },
    { name: 'Shirazuna Iwo', aliases: ['시라즈나 이오'] },
    { name: 'Tomyoji Kagura', aliases: ['토묘지 카구라'] },
    { name: 'Kototoi', aliases: ['코토토이'] },
    { name: 'Ayamo Nono', aliases: ['아야모 노노'] },

    // ── Re:AcT KR ─────────────────────────────────────────────────────
    { name: 'Majinai Kuroka', aliases: ['마지나이 쿠로카'] },
    { name: 'Midomido Mayo', aliases: ['미도미도 마요'] },
    { name: 'Seiroku Kira', aliases: ['세이로쿠 키라'] },
    { name: 'Aoto Latte', aliases: ['아오토 라떼'] },
    { name: 'Ten+Ten Tenx2', aliases: ['텐텐'] },
    { name: 'Asamiya Nao', aliases: ['아사미야 나오'] },
    { name: 'Yuusz Mumu', aliases: ['유즈 무무'] },

    // ── Re:AcT Gaming ─────────────────────────────────────────────────
    { name: 'Koyoi Inari', aliases: ['코요이 이나리'] },
    { name: 'Shirotae Toki', aliases: ['시로타에 토키'] },
    { name: 'Towan Kokoro', aliases: ['토와 코코로'] },
    { name: 'Awawa Iruka', aliases: ['아와와 이루카'] },
    { name: 'Kurono Suzu', aliases: ['쿠로노 스즈'] },
    { name: 'Tsuyuri Eru', aliases: ['츠유리 에루'] },
    { name: 'Lulunea Neruru', aliases: ['루루네아 네루루'] },

    // ── .LIVE(どっとライブ) 메인 브랜치 ──────────────────────────────
    { name: 'Dennou Shojo Siro', aliases: ['덴노 쇼조 시로'] },
    { name: 'Baacharu', aliases: ['바아챠루'] },
    { name: 'Kakyoin Chieri', aliases: ['카쿄인 치에리'] },
    { name: 'Kagura Suzu', aliases: ['카구라 스즈'] },
    { name: 'Carro Pino', aliases: ['카로 피노'] },
    { name: 'Mokota Mememe', aliases: ['모코타 메메메'] },
    { name: 'Yamato Iori', aliases: ['야마토 이오리'] },
    { name: 'Nanahoshi Milily', aliases: ['나나호시 미리리'] },
    { name: 'Rikumu', aliases: ['리쿠무'] },
    { name: 'Rurun Rururica', aliases: ['루룬 루루리카'] },

    // ── VPI Cafe(.LIVE 산하) ─────────────────────────────────────────
    { name: 'Himaji Pane', aliases: ['히마지 파네'] },
    { name: 'Izayoi Chihaya', aliases: ['이자요이 치하야'] },
    { name: 'Kito Misaki', aliases: ['키토 미사키'] },
    { name: 'Amagami Ame', aliases: ['아마가미 아메'] },
    { name: 'Sharaku Setsuna', aliases: ['샤라쿠 세츠나'] },
    { name: 'Gurenbatsu Maru', aliases: ['구렌바츠 마루'] },
    { name: 'Toboe Kyan', aliases: ['토보에 캬안'] },
    { name: 'Watanuki Neguse', aliases: ['와타누키 네구세'] },
    { name: 'Karasuma Pyoco', aliases: ['카라스마 표코'] },
    { name: 'Vermouth Belluna', aliases: ['베르무트 벨루나'] },
    { name: 'Kagimiya Ciel', aliases: ['카기미야 시엘'] },
    { name: 'Margher Richa', aliases: ['마르게르 리샤'] },
    { name: 'Gintoge Gumi', aliases: ['긴토게 구미'] },
    { name: 'Komachi Gabu', aliases: ['코마치 가부'] },
    { name: 'Saika Suiren', aliases: ['사이카 스이렌'] },
    { name: 'Nekonade Kozeni', aliases: ['네코나데 코제니'] },
    { name: 'Hachimitsu Purin', aliases: ['하치미츠 푸린'] },
    { name: 'Hanayuri Chumi', aliases: ['하나유리 츄미'] },
    { name: 'Yamada Nanoda', aliases: ['야마다 나노다'] },

    // ── Nijisanji KR ──────────────────────────────────────────────────
    { name: 'Min Suha', aliases: ['민수하'] },
    { name: 'Gaon', aliases: ['가온'] },
    { name: 'So Nagi', aliases: ['소나기'] },
    { name: 'Lee Roha', aliases: ['이로하'] },
    { name: 'Akira Ray', aliases: ['아키라 레이'] },
    { name: 'Yang Nari', aliases: ['양나리'] },
    { name: 'Ryu Hari', aliases: ['류하리'] },
    { name: 'Oh Jiyu', aliases: ['오지유'] },
    { name: 'Seffyna', aliases: ['세피나'] },
    { name: 'Na Sera', aliases: ['나세라'] },
    { name: 'Ha Yun', aliases: ['하윤'] },

    // ── StelLive (한국, 유튜브 라이브 확인 — Twitch 한국 차단 이후 유튜브가 주 플랫폼) ──
    { name: 'Ayatsuno Yuni', aliases: ['아야츠노 유니'] },
    { name: 'Sakihane Huya', aliases: ['사키하네 휴야'] },
    { name: 'Shirayuki Hina', aliases: ['시라유키 히나'] },
    { name: 'Neneko Mashiro', aliases: ['네네코 마시로'] },
    { name: 'Akane Lize', aliases: ['아카네 리제'] },
    { name: 'Arahashi Tabi', aliases: ['아라하시 타비'] },
    { name: 'Tenko Shibuki', aliases: ['텐코 시부키'] },
    { name: 'Aokumo Rin', aliases: ['아오쿠모 린'] },
    { name: 'Hanako Nana', aliases: ['하나코 나나'] },
    { name: 'Yuzuha Riko', aliases: ['유즈하 리코'] },

    // ── Nyantasia!(Sanrio×ClaN Entertainment) ────────────────────────
    { name: 'Nyamamugi Tart', aliases: ['냐마무기 타르트'] },
    { name: 'Nyamashiro Soda', aliases: ['냐마시로 소다'] },
    { name: 'Nyamafuji Anzu', aliases: ['냐마후지 안즈'] },
    { name: 'Nyamakage Neon', aliases: ['냐마카게 네온'] },
    { name: 'Nyamakumo Fuwari', aliases: ['냐마쿠모 후와리'] },
    { name: 'Nyamaharu Eru', aliases: ['냐마하루 에루'] },
    { name: 'Nyamashuva Lutz', aliases: ['냐마슈바 루츠'] },
    { name: 'Nyamalbelle Perle', aliases: ['냐마르벨 페를'] },

    // ── SCARZ / MeSTAGE ───────────────────────────────────────────────
    { name: 'Restia', aliases: ['레스티아'] },
    { name: 'Delutaya', aliases: ['델루타야'] },
    { name: 'Kirameki Eve', aliases: ['키라메키 이브'] },

    // ── Million Production(ミリプロ) ──────────────────────────────────
    { name: 'Amakami Konomi', aliases: ['아마카미 코노미'] },
    { name: 'Nonono Nono', aliases: ['노노노 노노'] },
    { name: 'Akubi Demonspade', aliases: ['아쿠비 데몬스페이드'] },
    { name: 'Otonose Raco', aliases: ['오토노세 라코'] },
    { name: 'Yuragi Yura', aliases: ['유라기 유라'] },
    { name: 'Nijipuka Nuhu', aliases: ['니지푸카 누후'] },
    { name: 'Komawari Koma', aliases: ['코마와리 코마'] },
    { name: 'Nemukumo Tsukuri', aliases: ['네무쿠모 츠쿠리'] },
    { name: 'Amayo Liz', aliases: ['아마요 리즈'] },
    { name: 'Yugiri Ray', aliases: ['유기리 레이'] },

    // ── MythosHQ ──────────────────────────────────────────────────────
    { name: 'Poseidon', aliases: ['포세이돈'] },
    { name: 'ApolloRyze', aliases: ['아폴로라이즈'] },
    { name: 'Ares', aliases: ['아레스'] },
    { name: 'Dionysus', aliases: ['디오니소스'] },
    { name: 'Aphrodite', aliases: ['아프로디테'] },
    { name: 'Thor Runefall', aliases: ['토르 룬폴'] },
    { name: 'Freyja Valdis', aliases: ['프레이야 발디스'] },
    { name: 'Loki Laufeydottir', aliases: ['로키 라우페이도티르'] },
    { name: 'Odin Ravenseye', aliases: ['오딘 레이븐아이'] },

    // ── V&U ───────────────────────────────────────────────────────────
    { name: 'Liora Walkyria', aliases: ['리오라 발키리아'] },
    { name: 'Yurikago Kokone', aliases: ['유리카고 코코네'] },
    { name: 'Amoria', aliases: ['아모리아'] },
    { name: 'Meeta Osita', aliases: ['미타 오시타'] },
    { name: 'D.K Graves', aliases: ['D.K 그레이브스'] },
    { name: 'Zeli Zuimu', aliases: ['젤리 주이무'] },
    { name: 'Misma Ryzing', aliases: ['미스마 라이징'] },
    { name: 'Cerenity Cosmica', aliases: ['세레니티 코스미카'] },
    { name: 'Rowa Arctos', aliases: ['로와 아르크토스'] },
    { name: 'Mivi Aivori', aliases: ['미비 아이보리'] },
    { name: 'Tomomi Toraya', aliases: ['토모미 토라야'] },
    { name: 'Ciccino Katterina', aliases: ['치치노 카테리나'] },

    // ── Varium ────────────────────────────────────────────────────────
    { name: 'Komai Ume', aliases: ['코마이 우메'] },
    { name: 'Suzutuki Sui', aliases: ['스즈츠키 스이'] },
    { name: 'Amemochi Nina', aliases: ['아메모치 니나'] },
    { name: 'Serenade Oxblood', aliases: ['세레나데 옥스블러드'] },
    { name: 'Watamiya Ahiru', aliases: ['와타미야 아히루'] },
    { name: 'Mishio Molf', aliases: ['미시오 몰프'] },
    { name: 'Siden Lime', aliases: ['시덴 라임'] },
    { name: 'Toono Oto', aliases: ['토오노 오토'] },
    { name: 'Anon Remu', aliases: ['아논 레무'] },
    { name: 'Unohana Nonochi', aliases: ['우노하나 노노치'] },
    { name: 'Kurea Shuri', aliases: ['쿠레아 슈리'] },
    { name: 'Arcana Grimmybear', aliases: ['아르카나 그리미베어'] },
    { name: 'Monica Melodia', aliases: ['모니카 멜로디아'] },
    { name: 'Himamori Pota', aliases: ['히마모리 포타'] },

    // ── Dynasty V ─────────────────────────────────────────────────────
    { name: 'Maruga Jakoji', aliases: ['마루가 자코지'] },
    { name: 'Lyri Kinoko', aliases: ['리리 키노코'] },
    { name: 'Mirajane', aliases: ['미라제인'] },

    // ── MOE!Live (영국) ───────────────────────────────────────────────
    { name: 'Louis', aliases: ['루이'] },
    { name: 'Mercury Asoge', aliases: ['머큐리 아소게'] },
    { name: 'Fangy', aliases: ['팽지'] },
    { name: 'Nap', aliases: ['냅'] },
    { name: 'Plushiepixie', aliases: ['플러시픽시'] },
    { name: 'Tori Thaiga', aliases: ['토리 타이가'] },

    // ── Vkano(舊 Propro Production) ──────────────────────────────────
    { name: 'Koinoya Mai', aliases: ['코이노야 마이'] },
    { name: 'Kyui Yui', aliases: ['큐이 유이'] },
    { name: 'Daraan Miavi', aliases: ['다란 미아비'] },
    { name: 'Homuraki Syana', aliases: ['호무라키 샤나'] },
    { name: 'Nekomiya Fuyu', aliases: ['네코미야 후유'] },

    // ══════════════════════════════════════════════════════════════════
    // 해외 휴먼(비-버튜버) 유튜브 라이브 스트리머 — 1000명 목표 중
    // 501~1000번째 구간. ikioi-ranking.com의 YouTube Live 실시간 동시접속자
    // 랭킹("VTuber以外" 필터, 2026-08-05 스냅샷 기준 — 그 시각 실제 라이브
    // 중이던 채널만 채택)과 Streams Charts의 2025~2026 유튜브 게이밍
    // 랭킹 기사로 확인한 채널만 담았다. 서구권 대형 스트리머(Kai Cenat,
    // AMP 크루, Jerma985, xQc, Asmongold 등)는 실제 주 플랫폼이
    // 트위치/Kick이라 제외했다. 1차분은 검증이 잘 된 일본(74명) +
    // 영어권(4명) 위주이며, 한국은 SOOP 독점계약 관행상 유튜브 전업
    // 스트리머 표본이 아직 부족해 보류(검증되는 대로 추가 예정).
    // ══════════════════════════════════════════════════════════════════

    // ── 일본 (ikioi-ranking.com YouTube Live 실시간 랭킹 확인) ─────────
    { name: 'FXマシーンくにお', aliases: ['FX 머신 쿠니오'] },
    { name: '兄者弟者', aliases: ['아니쟈 오토토'] },
    { name: 'かずのこチャンネル', aliases: ['카즈노코 채널'] },
    { name: 'ポッキー', aliases: ['포키'] },
    { name: 'ばぁう', aliases: ['바우'] },
    { name: 'SANNINSHOW', aliases: ['산닌쇼'] },
    { name: 'tekkenchannel', aliases: ['테켄채널'] },
    { name: 'TOPANGA', aliases: ['토판가'] },
    { name: 'tttcheekyttt', aliases: ['치키'] },
    { name: 'おおはらMEN', aliases: ['오오하라멘'] },
    { name: 'ドズル社', aliases: ['도즈루샤'] },
    { name: "Sho's投資情報局", aliases: ['쇼 투자정보국'] },
    { name: 'コジマ店員のホラーは恐くない', aliases: ['코지마텐인'] },
    { name: 'Taka room', aliases: ['타카룸'] },
    { name: 'あまくだり', aliases: ['아마쿠다리'] },
    { name: 'ハヤトの野望', aliases: ['하야토의 야망'] },
    { name: '一富士二鷹たこなすび', aliases: ['이치후지 니타카 타코나스비'] },
    { name: 'HikakinGames', aliases: ['히카킨게임즈'] },
    { name: 'マロン白書Crystal.', aliases: ['마론백서 크리스탈'] },
    { name: 'あっさりしょこ', aliases: ['앗사리쇼코'] },
    { name: 'Mondo', aliases: ['몬도'] },
    { name: '黒炭酸', aliases: ['쿠로탄산'] },
    { name: 'パラディン森永のリアル経済学', aliases: ['팔라딘 모리나가의 리얼경제학'] },
    { name: 'ちささこ', aliases: ['치사사코'] },
    { name: 'Leo the football TV', aliases: ['레오 더 풋볼 TV'] },
    { name: 'おついちTube', aliases: ['오츠이치튜브'] },
    { name: 'にゅるい', aliases: ['뉴루이'] },
    { name: 'アカgames', aliases: ['아카게임즈'] },
    { name: 'エぺ文句タケゾー', aliases: ['에페몬쿠 타케조'] },
    { name: 'ヴァッシュTV', aliases: ['바슈TV'] },
    { name: 'まぐろ', aliases: ['마구로'] },
    { name: '文化人放送局LIVE', aliases: ['분카진 방송국 라이브'] },
    { name: 'たすく', aliases: ['타스쿠'] },
    { name: '岐阜暴威', aliases: ['기후보이'] },
    { name: 'オタクチャンネル', aliases: ['오타쿠채널'] },
    { name: 'あきのちゃんねる', aliases: ['아키노채널'] },
    { name: '令和ちゃんねる', aliases: ['레이와채널'] },
    { name: 'ぷりっつ', aliases: ['프리츠'] },
    { name: 'ノゴローチャンネル', aliases: ['노고로채널'] },
    { name: '麻婆豆腐', aliases: ['마파두부'] },
    { name: 'るんば', aliases: ['룬바'] },
    { name: 'あゆみんch', aliases: ['아유밍채널'] },
    { name: 'たくまんBrainrot', aliases: ['타쿠만 브레인랏'] },
    { name: 'ふぅチャンネル', aliases: ['후채널'] },
    { name: 'ファルコン竹田です', aliases: ['팔콘 타케다입니다'] },
    { name: 'NullGame', aliases: ['널게임'] },
    { name: 'にぶちゃんねる', aliases: ['니부채널'] },
    { name: 'ノビーの遊び部屋', aliases: ['노비의 놀이방'] },
    { name: 'ゆちゃむ', aliases: ['유챠무'] },
    { name: 'ガンサーの抹茶', aliases: ['간사의 말차'] },
    { name: '羽衣狐あっと京おんぷ', aliases: ['하고로모키츠네 앗토쿄온푸'] },
    { name: 'シンのたわむれるチャンネル', aliases: ['신의 장난치는 채널'] },
    { name: 'ぶゅりる', aliases: ['뷰리루'] },
    { name: '小倉', aliases: ['코쿠라'] },
    { name: 'ぎこちゃん', aliases: ['기코짱'] },
    { name: '何屋未来', aliases: ['나니야미라이'] },
    { name: 'もあちゃんねる', aliases: ['모아채널'] },
    { name: '西鍋ん家', aliases: ['니시나벤치'] },
    { name: 'LuLuDiy Duo-JP', aliases: ['루루디아이듀오JP'] },
    { name: 'エスターク先輩のゲーム実況', aliases: ['에스타크 선배'] },
    { name: 'いぬねこ', aliases: ['이누네코'] },
    { name: 'ダメギ黒い人チャンネル', aliases: ['다메기 쿠로이히토채널'] },
    { name: 'AlphaAzur', aliases: ['알파아주르'] },
    { name: 'えいむくん', aliases: ['에임쿤'] },
    { name: 'ニート医師「井たくま」チャンネル', aliases: ['이타쿠마'] },
    { name: 'ワンちゅう', aliases: ['완츄'] },
    { name: 'らっこ侍', aliases: ['랏코사무라이'] },
    { name: 'ねこにら', aliases: ['네코니라'] },
    { name: 'ダヤン', aliases: ['다얀'] },
    { name: 'mozuku', aliases: ['모즈쿠'] },
    { name: 'ファミ通TUBE', aliases: ['파미통튜브'] },
    { name: '4YN しゆん', aliases: ['시윤'] },
    { name: 'スロカスパパ漢気くん', aliases: ['스로카스파파 칸키쿤'] },
    { name: '伊東ライフ', aliases: ['이토 라이프'] },

    // ── 영어권 (Streams Charts 2025~2026 유튜브 게이밍 랭킹 확인) ──────
    { name: 'IShowSpeed', aliases: ['아이쇼스피드'] },
    { name: 'DrDisrespect', aliases: ['닥터디스리스펙트'] },
    { name: 'Valkyrae', aliases: ['발키리'] },
    { name: 'Typical Gamer', aliases: ['티피컬 게이머'] },

    // ── 한국 (playboard.co 한국 유튜브 라이브 시청자 랭킹, 2026-08-04
    // 스냅샷 확인 — 카테고리별 상위권 중 방송사/공영 채널·종교 채널
    // 제외, 순수 음악 방송 제외) ─────────────────────────────────────
    { name: '김어준의 겸손은힘들다 뉴스공장', aliases: ['뉴스공장'] },
    { name: '[팟빵] 최욱의 매불쇼', aliases: ['매불쇼'] },
    { name: '삼프로TV 3PROTV', aliases: ['삼프로', '삼프로티비'] },
    { name: '오선의 미국 증시 라이브', aliases: ['오선 라이브'] },
    { name: '815머니톡', aliases: ['815머니톡'] },
    { name: '장르만 여의도', aliases: ['장르만여의도'] },
    { name: '박시영TV', aliases: ['박시영'] },
    { name: '머니코믹스 Money Comics', aliases: ['머니코믹스'] },
    { name: '1waynews 한길뉴스', aliases: ['한길뉴스'] },
    { name: '사장남천동', aliases: ['사장남천동'] },
    { name: '고성국TV', aliases: ['고성국'] },
    { name: '배승희 변호사', aliases: ['배승희'] },
    { name: '주식명사수 주명', aliases: ['주식명사수'] },
    { name: '채널A 김진의 돌직구쇼', aliases: ['김진의 돌직구쇼'] },
    { name: 'GROUND C 그라운드씨', aliases: ['그라운드씨'] },
    { name: '증시각도기TV', aliases: ['증시각도기'] },
    { name: '시사타파TV', aliases: ['시사타파'] },
    { name: '박성태의 뉴스쇼', aliases: ['박성태의 뉴스쇼'] },
    { name: '잼촌', aliases: ['잼촌'] },
    { name: '차래현', aliases: ['차래현'] },
    { name: '수삼티비', aliases: ['수삼티비'] },
    { name: '우주하마', aliases: ['우주하마'] },
    { name: '갈량이', aliases: ['갈량이'] },
    { name: '스트리머 사또', aliases: ['사또'] },
    { name: '쌈용', aliases: ['쌈용'] },
    { name: '멜로우TV', aliases: ['멜로우'] },
    { name: '원큐', aliases: ['원큐'] },
    { name: '기본수', aliases: ['기본수'] },
    { name: '안내메시지', aliases: ['안내메시지'] },
    { name: '홍가네', aliases: ['홍가네'] },
    { name: '깝도이', aliases: ['깝도이'] },
    { name: '중년게이머 김실장', aliases: ['김실장'] },
    { name: '비도', aliases: ['비도'] },
    { name: '사회인 게임클럽', aliases: ['사회인게임클럽'] },
    { name: '만리', aliases: ['만리'] },
    { name: '맛있는 녀석들', aliases: ['맛있는녀석들'] },
    { name: '봉이네집밥', aliases: ['봉이네'] },
    { name: '네모공장_카인', aliases: ['카인'] },
    { name: '알상무', aliases: ['알상무'] },
    { name: '곽준성', aliases: ['곽준성'] },
    { name: '돌비공포라디오', aliases: ['돌비공포라디오'] },
    { name: '노준', aliases: ['노준'] },
    { name: '목격자K', aliases: ['목격자케이'] },
    { name: '라오스 홍이형TV', aliases: ['홍이형'] },
    { name: '새로미', aliases: ['새로미'] },
    { name: '다썰남TV', aliases: ['다썰남'] },
    { name: '주덕', aliases: ['주덕'] },
    { name: '뱀충제', aliases: ['뱀충제'] },
    { name: '티끌 모아 홍이TV', aliases: ['티끌모아홍이'] },
    { name: '뿌리', aliases: ['뿌리'] },
    { name: '달수네라이브', aliases: ['달수네'] },
    { name: '블랙컴뱃', aliases: ['블랙컴뱃'] },
    { name: '크보오프너', aliases: ['크보오프너'] },
    { name: '이영우의 라이브 TV', aliases: ['이영우'] },
    { name: '크보쌍둥이', aliases: ['크보쌍둥이'] },
    { name: '어수홀덤TV', aliases: ['어수홀덤'] },
    { name: '흑자헬스', aliases: ['흑자헬스'] },
    { name: '새벽의 축구 전문가', aliases: ['새벽의축구전문가'] },
    { name: '불팬', aliases: ['불타는야구팬'] },
    { name: '여농티비', aliases: ['여농티비'] },
    { name: '야구부장', aliases: ['야구부장'] },
    { name: '당구해커', aliases: ['당구해커'] },
    { name: 'PIN GOLF', aliases: ['핀골프'] },
    { name: '김형준의 야구야구', aliases: ['야구야구'] },
    { name: '이글스 EVERYDAY', aliases: ['이글스에브리데이'] },
    { name: 'TwinSoul', aliases: ['트윈소울'] },
    { name: '선수탐구', aliases: ['선수탐구'] }
  ];

  const ALIAS_MAP = new Map();
  ENTRIES.forEach(({ name, aliases }) => {
    if (!name || !Array.isArray(aliases)) return;
    aliases.forEach((alias) => {
      const key = String(alias || '').trim().normalize('NFKC').toLowerCase();
      if (!key) return;
      // 같은 별칭이 두 채널에 중복 등록되면 먼저 등록된 쪽을 우선한다 —
      // 나중 항목이 조용히 덮어써 엉뚱한 채널로 매칭되는 걸 막기 위해서다.
      if (ALIAS_MAP.has(key) && ALIAS_MAP.get(key) !== name) {
        console.warn(`[CHEESE EYES][별칭 테이블] 별칭 "${alias}"가 "${ALIAS_MAP.get(key)}"와 "${name}" 양쪽에 등록돼 있습니다 — 먼저 등록된 "${ALIAS_MAP.get(key)}"를 유지합니다.`);
        return;
      }
      ALIAS_MAP.set(key, name);
    });
  });

  window.CHEESE_EYES_YOUTUBE_ALIASES = ALIAS_MAP;
})();
